import React, { useState, useEffect, useRef } from "react";
import { useNavigate, Navigate } from "react-router-dom";
import { NeonButton, GlassCard, C } from "../App";
import { supabase } from "../services/supabase";
import html2pdf from "html2pdf.js";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";

export default function DownloadPage({ user, isPaid, setPage, selectedTemplate }) {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loadingType, setLoadingType] = useState(null); // 'pdf' or 'docx'
  const invisibleContainerRef = useRef(null);

  useEffect(() => {
    async function loadData() {
      if (!selectedTemplate) return;
      let loaded = null;
      if (user) {
        const { data: dbData } = await supabase
          .from('resumes')
          .select('data')
          .eq('user_id', user.id)
          .eq('template_id', selectedTemplate.id)
          .maybeSingle();
        if (dbData && dbData.data) loaded = dbData.data;
      }
      if (!loaded) {
        const saved = localStorage.getItem('refox_resume_draft_' + selectedTemplate.id);
        if (saved) {
          try { loaded = JSON.parse(saved); } catch(e) {}
        }
      }
      setData(loaded || {});
    }
    loadData();
  }, [user, selectedTemplate]);

  if (!user) {
    return <Navigate to="/" replace />;
  }

  // Guard: if unpaid, redirect to payment
  if (!isPaid) {
    return <Navigate to="/payment" replace />;
  }

  if (!selectedTemplate || !data) {
    return <div style={{ color: '#fff', padding: 50, textAlign: 'center' }}>Loading... please wait.</div>;
  }

  const getFileName = (ext) => {
    const defaultName = 'resume';
    const base = user?.user_metadata?.full_name 
      ? user.user_metadata.full_name.replace(/\s+/g, "").toLowerCase() + 'resume'
      : defaultName;
    return `${base}.${ext}`;
  };

  const handleDownloadPDF = async () => {
    setLoadingType('pdf');
    try {
      if (!invisibleContainerRef.current) return;
      
      const htmlString = selectedTemplate.renderHTML(data);
      // We overwrite the inner HTML
      invisibleContainerRef.current.innerHTML = htmlString;

      // Extract the body content (ignore the doctype, html, head generated by template)
      // Since renderHTML returns full HTML document, we can extract just the markup or inject it into an iframe, 
      // but html2pdf can also take a DOM element directly.
      const doc = new DOMParser().parseFromString(htmlString, 'text/html');
      const element = doc.body;

      const opt = {
        margin:       0,
        filename:     getFileName('pdf'),
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
      };

      await html2pdf().set(opt).from(element).save();
    } catch(e) {
      alert("Failed to generate PDF.");
      console.error(e);
    }
    setLoadingType(null);
  };

  const handleDownloadWord = async () => {
    setLoadingType('docx');
    try {
      const layout = data.layout || [];
      const sections = [];

      // Include basic header from personal
      const personal = data.personal || {};
      sections.push(
        new Paragraph({
          text: personal.fullName || 'Name',
          heading: HeadingLevel.TITLE,
        }),
        new Paragraph({
          text: [personal.professionalTitle, personal.currentRole, personal.subhead].filter(Boolean).join(' | '),
          heading: HeadingLevel.HEADING_2,
        })
      );

      // Contact
      const contacts = [personal.email, personal.phone, personal.location, personal.linkedin].filter(Boolean).join(' | ');
      if (contacts) {
        sections.push(new Paragraph({ text: contacts }));
      }
      
      sections.push(new Paragraph({ text: "" })); // spacing

      // Iterate layout
      layout.forEach(sec => {
         if (sec.id === 'personal' || sec.id === 'footer') return;
         
         const secData = data[sec.id];
         if (!secData) return;

         sections.push(
            new Paragraph({
              text: sec.label.toUpperCase(),
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 200, after: 100 }
            })
         );

         if (sec.type === 'textarea') {
            sections.push(new Paragraph({ text: secData }));
         } else if (Array.isArray(secData)) {
            secData.forEach(item => {
               if (sec.type === 'exp-repeater') {
                 sections.push(new Paragraph({ children: [
                    new TextRun({ text: item.jobTitle || '', bold: true }),
                    new TextRun({ text: item.company ? ` | ${item.company}` : '', bold: true }),
                    new TextRun({ text: `\t${item.startDate || ''} - ${item.endDate || ''}` }) // Quick tab align hack
                 ]}));
                 if (item.bullets) {
                    const bullets = typeof item.bullets === 'string' ? item.bullets.split('\n') : item.bullets;
                    bullets.forEach(b => {
                      if (b.trim()) sections.push(new Paragraph({ text: b.trim(), bullet: { level: 0 } }));
                    });
                 }
               } else if (sec.type === 'bullet-repeater') {
                 if (item.text) sections.push(new Paragraph({ text: item.text, bullet: { level: 0 } }));
               } else if (sec.type === 'edu-repeater') {
                 sections.push(new Paragraph({ children: [
                    new TextRun({ text: item.degree || '', bold: true }),
                    new TextRun({ text: item.school ? ` - ${item.school}` : '' }),
                 ]}));
               } else if (sec.type === 'project-repeater') {
                 sections.push(new Paragraph({ children: [
                    new TextRun({ text: item.title || '', bold: true }),
                 ]}));
                 const bullets = typeof item.bullets === 'string' ? item.bullets.split('\n') : (item.bullets || []);
                 bullets.forEach(b => {
                    if (b.trim()) sections.push(new Paragraph({ text: b.trim(), bullet: { level: 0 } }));
                 });
                 if (item.description) sections.push(new Paragraph({ text: item.description }));
               } else if (sec.type === 'skills-repeater') {
                 sections.push(new Paragraph({ children: [
                    new TextRun({ text: `${item.category}: `, bold: true }),
                    new TextRun({ text: item.items || '' }),
                 ]}));
               }
            });
         }
      });

      const doc = new Document({
        sections: [{ properties: {}, children: sections }]
      });

      const blob = await Packer.toBlob(doc);
      // Wait, file-saver is needed, let's just use native DOM anchor for saving
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      document.body.appendChild(a);
      a.style = "display: none";
      a.href = url;
      a.download = getFileName('docx');
      a.click();
      window.URL.revokeObjectURL(url);
    } catch(e) {
      alert("Failed to generate Word document.");
      console.error(e);
    }
    setLoadingType(null);
  };

  return (
    <div style={{ minHeight: "100vh", paddingTop: 100, display: "flex", flexDirection: "column", alignItems: "center", position: "relative", overflow: "hidden" }}>
      <div style={{ maxWidth: 640, width: "100%", margin: "0 auto", padding: "40px 24px", position: "relative", zIndex: 10 }}>
        <div style={{ textAlign: "center", marginBottom: 40, animation: "fadeUp 0.6s ease forwards" }}>
          <h1 className="headline" style={{ fontSize: "clamp(32px,5vw,56px)", fontWeight: 900, letterSpacing: "-0.04em", marginBottom: 12 }}>
            Download <span className="neon" style={{ color: C.primary, fontStyle: "italic" }}>Unlocked</span>
          </h1>
          <p style={{ color: C.mutedLight, fontSize: 16 }}>Your paid access is active. Download your resume in high quality without watermarks.</p>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
          <GlassCard style={{ padding: 40, textAlign: 'center' }}>
            <div style={{ fontSize: 40, marginBottom: 20 }}>📄</div>
            <h3 className="headline" style={{ fontSize: 24, fontWeight: 800, marginBottom: 12 }}>Print-Ready ATS PDF</h3>
            <p style={{ color: C.mutedLight, fontSize: 14, marginBottom: 24 }}>Pixel-perfect, uneditable format guaranteed to pass through ATS parsers cleanly.</p>
            <NeonButton size="lg" onClick={handleDownloadPDF} disabled={loadingType === 'pdf'} style={{ width: '100%' }}>
               {loadingType === 'pdf' ? "Generating PDF..." : "Download as PDF"}
            </NeonButton>
          </GlassCard>

          <GlassCard style={{ padding: 40, textAlign: 'center' }}>
            <div style={{ fontSize: 40, marginBottom: 20 }}>📝</div>
            <h3 className="headline" style={{ fontSize: 24, fontWeight: 800, marginBottom: 12 }}>Editable MS Word (.docx)</h3>
            <p style={{ color: C.mutedLight, fontSize: 14, marginBottom: 24 }}>Standard format containing all your content, fully editable in Microsoft Word or Google Docs.</p>
            <NeonButton size="lg" variant="outline" onClick={handleDownloadWord} disabled={loadingType === 'docx'} style={{ width: '100%' }}>
               {loadingType === 'docx' ? "Generating Word..." : "Download as Word (.docx)"}
            </NeonButton>
          </GlassCard>
        </div>
        
        <div style={{ textAlign: 'center', marginTop: 32 }}>
          <button onClick={() => navigate(`/preview`)} style={{ background: "transparent", color: C.primary, border: "none", cursor: "pointer", fontSize: 14, textDecoration: "underline" }}>
            Return to Preview
          </button>
        </div>
      </div>
      <div ref={invisibleContainerRef} style={{ display: 'none' }} />
    </div>
  );
}
